### ISSUE TITLE
how to pass arguments to the task function. 

### ISSUE THREAD

**Issue by palparam** [aleksve/ischedule#18]
Hi I tried with below code but getting error.

from ischedule import schedule, run_loop
from datetime import timedelta
from threading import Event

stop_event = Event()
counter = 0
def bot(name='There'):
    global counter
    counter += 1
    wish = "Hi " + name + " !!!"
    print(f"{counter}. {wish}")
    
    if counter>=3:
        print("Counter Reached")
        stop_event.set()
   
schedule(bot('Pal'), interval=timedelta(seconds=1))
run_loop(stop_event = stop_event)

Output:
1. Hi Pal!!!
Traceback (most recent call last):
  File "C:\work\temp1.py", line 26, in <module>
    run_loop(stop_event = stop_event)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\ischedule\ischedule.py", line 117, in run_loop
    stop_event.wait(next_call_time)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timestamp too large to convert to C _PyTime_t

**Comment by aleksve** [comment]
Hello @palparam. Sorry about the late answer. As it stands, `ischedule` doesn't support task functions with parameters. You can solve it by defining 

```python
def bot_Pal():
  bot('Pal')
```

After that, you can do ```schedule(bot_Pal, interval=timedelta(seconds=1))```, which I think does what you wanted. You could also generate task functions dynamically with [```functools.partial```](https://docs.python.org/3/library/functools.html).
